; Seeed Studio XIAO ESP32-C6
; https://docs.platformio.org/en/latest/boards/espressif32/seeed_xiao_esp32c6.html

[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino

monitor_speed = 115200

; USB serial upload (default). Override if you use a different adapter:
; upload_protocol = esptool
